---


basebox:
  name: basebox
  user: vagrant 
  password: vagrant 
  public_key: ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key
  mem: 1024
  cpu: 1
  location: http://archive.ubuntu.com/ubuntu/dists/wily/main/installer-amd64/
  preseed: preseed.cfg 
  extra_args: "locale=en_GB.UTF-8 console-setup/ask_detect=false keyboard-configuration/layoutcode=en file=file:/preseed.cfg vga=788 quiet"
  os:
    type: linux
    variant: ubuntuutopic
  virt_hypervisor: hvm
  virt_type: kvm
  disk:
    size: 4
    path: "{{ansible_user_dir}}/disks" 
